version: '3.9'
services:
  url:
    build:
      dockerfile: dockerfile.prod
      context: .
    entrypoint: npm run start:prod url
    depends_on:
      - mariadb
    networks:
      - my-bridge-network
  user:
    build:
      dockerfile: dockerfile.prod
      context: .
    entrypoint: npm run start:prod user
    depends_on:
      - mariadb
    networks:
      - my-bridge-network

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./swagger-ui:/usr/share/nginx/html/docs
    depends_on:
      - user
      - url
    networks:
      - my-bridge-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-bridge-network

networks:
  my-bridge-network: # Defina uma rede personalizada
    driver: bridge
