version: '3.9'
services:
  url:
    build:
      dockerfile: dockerfile.prod
      context: .
    entrypoint: npm run start url
    networks:
      - my-bridge-network
  user:
    build:
      dockerfile: dockerfile.prod
      context: .
    entrypoint: npm run start user
    networks:
      - my-bridge-network

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx.prod
    depends_on:
      - user
      - url
    networks:
      - my-bridge-network

networks:
  my-bridge-network: # Defina uma rede personalizada
    driver: bridge
