version: '3.9'
services:
  url: 
    build: 
      dockerfile: dockerfile
      context: .
    entrypoint: npm run start:dev encurta-url
    volumes:
      - ./:/app
    networks:
      - my-bridge-network
  usuarios: 
    build: 
      dockerfile: dockerfile
      context: .
    entrypoint: npm run start:dev usuario
    volumes:
      - ./:/app
    networks:
      - my-bridge-network

  nginx:
    image: nginx:stable
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - usuarios
      - url
    networks:
      - my-bridge-network


  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-bridge-network

networks:
  my-bridge-network:  # Defina uma rede personalizada
    driver: bridge