version: '3.9'
services:
  krakend:
    image: devopsfaith/krakend:2.4
    container_name: krakend
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]


  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    ports:
      - "3306:3306"
    networks:
      - my-bridge-network

networks:
  my-bridge-network:  # Defina uma rede personalizada
    driver: bridge