openapi: 3.0.3
info:
  title: URL Service API
  version: 0.4.6

paths:
  /:
    get:
      summary: Lists user's URLs
      tags: [Url]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of URLs

    post:
      summary: Creates a shortened URL
      tags: [Url]
      security:
        - optionalBearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUrlDto'
      responses:
        '201':
          description: URL successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string

  /{code}:
    get:
      summary: Redirects to the original URL
      tags: [Url]
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirection

  /user:
    post:
      summary: Creates a user
      tags: [User]
      security:
        - optionalBearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string

  /user/login:
    post:
      summary: Logs in a user
      tags: [User]
      security:
        - optionalBearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: User successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    optionalBearerAuth:
      type: http
      scheme: bearer

  schemas:
    CreateUrlDto:
      type: object
      properties:
        url:
          type: string
          format: uri
      required:
        - url

    UpdateUrlDto:
      type: object
      properties:
        url:
          type: string
          format: uri

    CreateUserDto:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - email
        - password

    LoginDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    LoginResponseDto:
      type: object
      properties:
        accessToken:
          type: string
      required:
        - accessToken
